version: '3.8'

services:
  svelte:
    build: ./frontend
    ports:
      - "80:5000"
    depends_on:
      - express
    env_file: "./frontend/.env"

  express:
    build: ./backend
    ports:
      - "3001:3000"
    env_file: "./backend/.env"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - svelte
      - express
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

